const oldLabels = [
  "Admin Dashboard",
  "Area Detection",
  "Assets and Infrastructure",
  "Backend",
  "Blocked", //
  "Candor",
  "Cenlar",
  "Change Request",
  "Dependent",
  "Deployment",
  "Design Doc Pre",
  "Design Doc Req", //
  "Dev :: In-Progress",
  "Dev :: Ready-to-Qa",
  "Dev :: Resolved",
  "Dev :: Resolved QA",
  "Dev :: To-do",
  "DevOps",
  "E-sign",
  "Env :: Dev",
  "Env :: Prod",
  "Env :: QA",
  "Env :: Stage",
  "Environment setup",
  "Epic",
  "FAIL",
  "Flueid",
  "Frontend",
  "Gold Code",
  "HotFix",
  "Incident",
  "Load Testing",
  "ML Integration",
  "ML_AI",
  "Node",
  "Not Reproducible",
  "OCR Training",
  "On-Hold",
  "Operations",
  "Operations Dashboard",
  "PF",
  "PR Utility",
  "QA :: Bug",
  "QA :: Fixed",
  "QA :: Passed",
  "QC :: Bug",
  "R&D",
  "Recurring",
  "Refactor",
  "Security",
  "TBD",
  "TCX", //
  "Test Cases", //
  "Testing Not Required",
  "Tuning",
  "UX",
  "Use Case",
  "Critical-Priority",
  "High-Priority",
  "High-Severity",
  "iPad",
  "Low-Priority",
  "Low-Severity",
  "Medium-Priority",
  "Medium-Severity",
  "has context menu",
];

export { oldLabels };